### ISSUE TITLE
Identify and Fix Gaps in Sphinx Documentation

### ISSUE THREAD

**Issue by charlesdrotar** [tgsmith61591/skutil#12]
The intention for this issue is that it will be a reoccurring issue that would be recreated relative to each milestone. I think it is worth creating a new one each time to ensure that the new functionality for each milestone is captured and to also not get to a point where we gloss over this. In addition to what is below there will be some different types of issues that will be identified through the course of investigation and comparison of the results of ```make clean html```.

Currently some areas of focus are:

Missing Information
==============

 1) Methods sections in various classes should have their docstrings present
--------------------------------------------------------------------------
![screen shot 2016-10-12 at 9 15 01 am](https://cloud.githubusercontent.com/assets/3826821/19313520/607021a2-905c-11e6-96d4-5d61152e1933.png)

2) Missing Parameters in Docstrings that are present in function definition
--------------------------------------------------------------------------
![screen shot 2016-10-12 at 9 25 12 am](https://cloud.githubusercontent.com/assets/3826821/19313944/e68f60d0-905d-11e6-8af3-8fa8b951d1a5.png)

3) Gaps in Documentation altogether (due to sphinx not pulling them in properly or it not being present)
------------------------------------------------------------------------------------------
![screen shot 2016-10-12 at 9 31 30 am](https://cloud.githubusercontent.com/assets/3826821/19314150/bc8bb80a-905e-11e6-842d-282e63813113.png)

Formatting
========

1) Highlighting
--------------
![screen shot 2016-10-12 at 9 16 49 am](https://cloud.githubusercontent.com/assets/3826821/19313611/b6fdbb9c-905c-11e6-92e1-27f057c12b7f.png)

2) Typographical Mistakes that Lead to Weird Formatting
-------------------------------------------------------
![screen shot 2016-10-12 at 9 35 54 am](https://cloud.githubusercontent.com/assets/3826821/19314331/5b5759e4-905f-11e6-9388-ebba5ad18f53.png)

3) Spacing Issues
------------------
I have not identified any, but I imagine that they are present.

**Comment by charlesdrotar** [comment]
I think due to the nature of this problem it would be good to tackle this not by type of error but instead by file/package. Otherwise there will be potential for needless duplication of efforts so we will use the checkbox method to delineate completion of sub-issues in this issue. Each subissue will reflect a package within skutil or a oneoff script.

- [ ] skutil
  - [ ] decomposition
  - [ ] feature_selection
  - [ ] h2o
  - [ ] linear_model
  - [ ] metrics
  - [ ] model_selection
  - [ ] odr
  - [ ] preprocessing
  - [ ] utils
  - [ ] base.py
  - [ ] grid_search.py

This will help also in the ball rolling in terms of splitting the problem so that we can easily communicate what sections we each focus on :).

**Comment by tgsmith61591** [comment]
Addressed in 65ca67f. Still need a bit more doc in `skutil.h2o`, but it's pretty good for now. Will add more examples in later commits.
