### ISSUE TITLE
Improving Adherence to PEP8 Standards in codebase

### ISSUE THREAD

**Issue by charlesdrotar** [tgsmith61591/skutil#13]
This issue will be a reoccurring issue that will reemerge closer to milestone dates for releases. For now these are some major areas that should/could be considered are:
- Unused code
  - parameters
  - docstring parameters
  - imports
- Formatting
  - Indentation
  - Arguments/Variables should be in lowercase
  - Spacing between class methods and classes/functions themselves
- Implementing all function from an abstract class

<img width="548" alt="screen shot 2016-10-12 at 9 59 55 am" src="https://cloud.githubusercontent.com/assets/3826821/19315292/b63edce4-9062-11e6-8c8a-29a95c155419.png">
- Instance attributes defined external to the init of a class.
  - This is kind of self explanatory :)
- Tests for membership

<img width="450" alt="screen shot 2016-10-12 at 9 54 36 am" src="https://cloud.githubusercontent.com/assets/3826821/19315033/e955bde2-9061-11e6-8349-76a4bfd00984.png">
- Unresolved Attribute References

<img width="482" alt="screen shot 2016-10-12 at 9 56 16 am" src="https://cloud.githubusercontent.com/assets/3826821/19315130/2b892302-9062-11e6-811a-b141a7b3f299.png">
- Test for Object Identity

<img width="688" alt="screen shot 2016-10-12 at 9 58 31 am" src="https://cloud.githubusercontent.com/assets/3826821/19315214/77b6fd30-9062-11e6-875a-0bda1aea07a9.png">

**Comment by charlesdrotar** [comment]
I imagine certain things like lowercase versus uppercase will be somewhat excusable to adhere to sklearn / H2O conventions for familiarities sake. This is intended as more of a guideline/spotlight than Hammurabi's Code (pun intended).

**Comment by charlesdrotar** [comment]
I think due to the nature of this problem it would be good to tackle this not by type of error but instead by file/package. Otherwise there will be potential for needless duplication of efforts so we will use the checkbox method to delineate completion of sub-issues in this issue. Each subissue will reflect a package within skutil or a oneoff script.

- [ ] skutil
  - [ ] decomposition
  - [ ] feature_selection
  - [ ] h2o
  - [ ] linear_model
  - [ ] metrics
  - [ ] model_selection
  - [ ] odr
  - [ ] preprocessing
  - [ ] utils
  - [ ] base.py
  - [ ] grid_search.py

This will help also in the ball rolling in terms of splitting the problem so that we can easily communicate what sections we each focus on :).

**Comment by charlesdrotar** [comment]
Closing for now with [PR#17](https://github.com/tgsmith61591/skutil/pull/17). Will open similar issue when/if code begins to diverge from being compliant.

**Comment by charlesdrotar** [comment]
Actually leaving open as a reminder for some of the other changes that can be implemented.

**Comment by tgsmith61591** [comment]
Finished in 329d291 and its parent.
