### ISSUE TITLE
Running Tests as a matrix of scikit-learn 0.17/0.18 and python 2.7/3.5

### ISSUE THREAD

**Issue by charlesdrotar** [tgsmith61591/skutil#28]
Currently the version of scikit-learn [.travis.yml](https://github.com/tgsmith61591/skutil/blob/develop/.travis.yml#L36) defaults to scikit-learn 0.18. As a result the test cases do not test for scikit-learn version 0.17. 

The tricky part is to have a matrix of the four possible configurations of scikit-learn / python versions similar to [scikit-learn's .travis.yml](https://github.com/scikit-learn/scikit-learn/blob/master/.travis.yml). Another reference is from the [travis docs](https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)) themselves. 

Between these and some other docs yet to be found this should be something we could manage.

**Comment by charlesdrotar** [comment]
This runs in parallel to [issue#2](https://github.com/tgsmith61591/skutil/issues/2), which is specific to Python 3.5 travis integration.

**Comment by tgsmith61591** [comment]
The sklearn 0.17/0.18 test issue was handled in 69d4660... Closing out since we have the duplicate issue #2
