### ISSUE TITLE
gh-pages release num

### ISSUE THREAD

**Issue by tgsmith61591** [tgsmith61591/skutil#29]
Since `make clean html` depends on a built copy of skutil (using `python setup.py develop`), the egg info is in the skutil directory. Thus, it's pointing to a stale version. We need to merge master into gh-pages in our automation process or rebase it or something so that the version is updated at build time...

**Comment by charlesdrotar** [comment]
So there are two ways of doing it:

1.  The easy way is to just throw `python setup.py develop` in prior to `make clean html` within [publish_gh_pages.sh](https://github.com/tgsmith61591/skutil/blob/develop/doc/publish_gh_pages.sh)
2. The more proper way is to wire this up [automagically on commit to master](http://nikhilism.com/post/2012/automatic-github-pages-generation-from/), which I believe is possible, but non-trivial.

**Comment by charlesdrotar** [comment]
[pull#30](https://github.com/tgsmith61591/skutil/pull/30) should address the issue with building to gh-pages using approach #1.

**Comment by tgsmith61591** [comment]
Fixed on master in 7cab676
