### ISSUE TITLE
H2O model persistence - autogen main class

### ISSUE THREAD

**Issue by tgsmith61591** [tgsmith61591/skutil#31]
Downloading a POJO is actually kind of complicated&mdash;it still requires the user to build a main class. Can we write a class that will auto-gen and completely jar up a main class/method?

**Comment by charlesdrotar** [comment]
Have you ever used [jinja](http://jinja.pocoo.org/)? Its sole purpose is for templating in python. I believe we could autogen the java main class from a template using jinja, but I don't think this will be trivial. Here is a [primer on jinja templating](https://realpython.com/blog/python/primer-on-jinja-templating/). 

@tgsmith61591  Feedback?

**Comment by tgsmith61591** [comment]
@charlesdrotar yeah, not going to be easy. But certainly will be a cool&mdash;and extremely useful&mdash;feature.

**Comment by charlesdrotar** [comment]
This is the primer of sorts for jinja templating - [jinja template guide](http://jinja.pocoo.org/docs/dev/templates/).

**Comment by charlesdrotar** [comment]
Also it seems like if we want this all to run in an automated fashion we may want to consider doing some kind of subprocess call or something in that vein to chain the template generation to the fat-jarring since we are invoking various commands that are CLI-based.

**Comment by tgsmith61591** [comment]
H2O is moving away from POJOs and towards MOJOs. Let's move away from the Java templating; maybe at some point we can tie MOJOs in with skutil.
