### ISSUE TITLE
Errors in importing classes

### ISSUE THREAD

**Issue by RedLiN5** [tgsmith61591/skutil#36]
I tried to call _BoxCoxTransformer_ class following examples on [transformers in skutil](https://tgsmith61591.github.io/skutil/rsts/examples/transformers.html).
But I got an error like this:
```python
>>> from skutil.preprocessing import BoxCoxTransformer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Leslie/anaconda3/lib/python3.5/site-packages/skutil/preprocessing/__init__.py", line 7, in <module>
    from .balance import *
  File "/Users/Leslie/anaconda3/lib/python3.5/site-packages/skutil/preprocessing/balance.py", line 268, in <module>
    class _BaseBalancer(six.with_metaclass(abc.ABCMeta, object, BalancerMixin)):
  File "/Users/Leslie/anaconda3/lib/python3.5/site-packages/sklearn/externals/six.py", line 566, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Users/Leslie/anaconda3/lib/python3.5/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases object, BalancerMixin
```
It never happened to me. So anyone has ideas to solve it? 
Thanks!

**Comment by tgsmith61591** [comment]
What version skutil are you using?

**Comment by RedLiN5** [comment]
```python
>>> print(skutil.__version__)
0.1.3
```
I downloaded the module from your Github yesterday, and installed it via _setup.py_.

**Comment by tgsmith61591** [comment]
Thanks for bringing this up. We're about to release 0.1.5 and it should fix
this.

**Comment by RedLiN5** [comment]
Thanks! Looking forward to it lol!

**Comment by tgsmith61591** [comment]
Btw I notice you're using Python 3. Skutil has not *formally* been designed
for py3 yet (it's a work in progress) so some issues might be related to
that. We're working on replicating issue in python 3 with anaconda.

On Dec 22, 2016 6:09 PM, "Leslie_Yan" <notifications@github.com> wrote:

Thanks! Looking forward to it lol!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tgsmith61591/skutil/issues/36#issuecomment-268938071>,
or mute the thread

**Comment by charlesdrotar** [comment]
@RedLiN5,
I tested the import on the develop branch by running ``from skutil.preprocessing import BoxCoxTransformer`` using Python 3.5.2 and it executed successfully. Cutting the new release should address this issue you are seeing on the master branch.

**Comment by tgsmith61591** [comment]
Charles please merge develop into release-0.1.5 and file a PR into master.
I'll merge and then you can take care of gh-pages

**Comment by tgsmith61591** [comment]
0.1.5 was just released and should address this issue. All of our CI tests are passing... please let me know if you continue to encounter this issue.

**Comment by RedLiN5** [comment]
Thank you guys a lot! I have installed it, it's great to use ha! lol
